env:
    credentials: "ENCRYPTED[!44cce1d90a257aaadf987085df6632d32e443821c70631809cfea1f63ca0b4c40209a0c41986fd7a37c8f2e9461c3ac0!]"
    rcloneconfig: "ENCRYPTED[!00cf6389ac5fd7df9e2671ae4649f9746d40e7c8651882e85a852cb2cb8b9a512955a2cae554180cd672549121ffd683!]"
    tokentl: "ENCRYPTED[!92afde98545a929998ed742f4d86bcad35871a710b4c994851ddd95073a76119ac895677e140efe9eb82e8788b0981d4!]"
    idtl: "ENCRYPTED[!96d32487cfcdd969e6736ada7dd2c4713238d06db52b16fa996a2b256d52d09a27ddeada2267065a3f6499c0056777b5!]"
    lunch: lunch qassa_X01BD-userdebug
    make: make qassa

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "thrdchld"
       - git config --global user.email "thirdchilddesigner@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy qassa:qassa/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync qassa Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/keepQASSA/manifest.git -b Q -g default,-mips,-darwin,-notdefault
      - git clone --depth 1 https://github.com/thrdchld/local_manifest_new.git -b qassa-vanilla .repo/local_manifests
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/qassa.xml
#      - repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
      - sed -i 's| -u||g' vendor/qassa/config/branding.mk
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="thrdchld"
      - export BUILD_HOSTNAME="cirrus-ci"
      - export KBUILD_BUILD_USER="thrdchld"
      - export KBUILD_BUILD_HOST="cirrus-ci"
      - export BUILD_BROKEN_MISSING_REQUIRED_MODULES=true
      - export ALLOW_MISSING_DEPENDENCIES=true
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build qassa for X01BD Started!"
      - ./collect.sh
      - rclone copy ~/rom/out/target/product/X01BD/qassa*.zip qassa:qassa -P
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/X01BD/ && ls qassa*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz qassa:qassa -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"

